[package]
name = "dendrite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
itertools = "0.12.0"
rand = "0.8.5"

[lib]
doctest = false
